services:
  database:
    container_name: database
    build:
      dockerfile: dockerfile
      context: ./infra/postgres
    restart: always
    environment:
      POSTGRES_USER: saga-flight
      POSTGRES_PASSWORD: saga-flight
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./infra/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    entrypoint: docker-entrypoint.sh -c 'config_file=/etc/postgresql/postgresql.conf'

  adminer:
    container_name: adminer
    image: adminer:4
    depends_on:
      - database
    restart: always
    ports:
      - "3002:8080"

  setup:
    container_name: setup
    build:
      dockerfile: dockerfile
      context: ./infra/setup
    volumes:
      - ./infra/setup/setup.py:/setup/setup.py
    depends_on:
      - database

  server:
    container_name: server
    build:
      dockerfile: dockerfile
      context: ./src
    environment:
      - ENV=PRD
      - DB_ADDR=database
      - PG_DATABASE=saga-flight
      - PG_USER=saga-flight
      - PG_PASSWORD=saga-flight
      - JWT_SECRET=secret
    ports:
      - "3000:8080"
    depends_on:
      - database
    volumes:
      - ./server/cmd:/app/cmd
      - ./server/internal:/app/internal
volumes:
  pg-data:
  es-data:
  kbn-data:
