FROM python:3.8-alpine3.14

# Install dependencies
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev

COPY ./ /setup

WORKDIR /setup

RUN pip install psycopg2-binary

CMD [ "python", "setup.py"]