# build the server
FROM golang:latest as build

WORKDIR /app

COPY ./ ./

RUN go install github.com/DataDog/orchestrion@latest

RUN orchestrion pin

RUN orchestrion go mod download

RUN orchestrion go build -o bin/server main.go

ENTRYPOINT [ "./bin/server" ]
