## Hotel
# Create a new hotel
# @name createHotel
POST http://localhost:3001/hotels
Content-Type: application/json

{
  "name": "Hotel California",
  "location": "Los Angeles, CA",
  "rating": 5,
  "roomsAvailable": 100
}

###

# Get all hotels
GET http://localhost:3001/hotels
Content-Type: application/json

###

# Get a hotel by ID
GET http://localhost:3001/hotels/{{createHotel.response.body.hotelId}}
Content-Type: application/json

###

# Delete a hotel by ID
DELETE http://localhost:3001/hotels/some-hotel-id
Content-Type: application/json

###

## Hotel Booking
# Create a new hotel booking
# @name createBooking
POST http://localhost:3001/bookings
Content-Type: application/json

{
  "hotelId": "b003d4e3-ace4-4870-b1b0-7fb195f6f95d",
  "checkInDate": "2023-10-01T14:00:00Z",
  "checkOutDate": "2023-10-05T11:00:00Z",
  "customerName": "John Doe",
  "customerEmail": "john.doe@example.com",
  "roomNumber": 99
}

###

# Get all hotel bookings
GET http://localhost:3001/bookings?bookingStatus=active&hotelId={{createHotel.response.body.hotelId}}&customerEmail=john.doe@example.com
Content-Type: application/json

###

# Get a hotel booking by ID
GET http://localhost:3001/bookings/{{createBooking.response.body.bookingId}}
Content-Type: application/json

###

# Delete a hotel booking by ID
DELETE http://localhost:3001/bookings/{{createBooking.response.body.bookingId}}
Content-Type: application/json