## Flight
# Create a new flight
# @name createFlight
POST http://localhost:3000/flights
Content-Type: application/json

{
  "airline": "AirlineName",
  "origin": "OriginCity",
  "destination": "DestinationCity",
  "departureTime": "2023-10-01T10:00:00Z",
  "arrivalTime": "2023-10-01T12:00:00Z",
  "capacity": 320
}

###

# Get all flights
GET http://localhost:3000/flights
Content-Type: application/json

###

# Get a flight by ID
GET http://localhost:3000/flights/{{createFlight.response.body.flightId}}
Content-Type: application/json

###

# Delete a flight by ID
DELETE http://localhost:3000/flights/{{createFlight.response.body.flightId}}
Content-Type: application/json

###

## Booking
# Create a new booking
# @name createBooking
POST http://localhost:3000/bookings
Content-Type: application/json

{
  "flightId": "{{createFlight.response.body.flightId}}",
  "customerName": "John Doe",
  "customerEmail": "john.doe@example.com",
  "seatNumber": 13
}

###

# Get all bookings
GET http://localhost:3000/bookings?bookingStatus=active&flightId={{createFlight.response.body.flightId}}&customerEmail=john.doe@example.com
Content-Type: application/json

###

# Get a booking by ID
GET http://localhost:3000/bookings/{{createBooking.response.body.bookingId}}
Content-Type: application/json

###

# Delete a booking by ID
DELETE http://localhost:3000/bookings/{{createBooking.response.body.bookingId}}
Content-Type: application/json